# site settings
title: Zonily Jame Pesquera
subtitle: Mobile Software Developer 
email: zonilyjame@gmail.com
description: Builds Mobile applications. Active in tech communities
baseurl: # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Zonily Jame Pesquera
street_address: 
city: 
state: 
zip_code: 
country: 
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# social settings
500px_url:
facebook_url: https://www.facebook.com/zonilyjame
github_url: https://github.com/kuyazee
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com/kuyazee
linkedin_url: https://www.linkedin.com/in/zonilyjame
pinterest_url:
slack_url:
twitter_url: https://twitter.com/zonilyjame

# build settings
markdown: kramdown

sass:
  style: compressed

# PWA
pwa:
  sw_src_filepath: service-worker.js # Optional
  sw_dest_filename: service-worker.js # Optional
  dest_js_directory: assets/js # Required
  precache_recent_posts_num: 5 # Optional
  precache_glob_directory: / # Optional
  precache_glob_patterns: # Optional
    - "{js,css,fonts}/**/*.{js,css,eot,svg,ttf,woff}"
    - index.html
  precache_glob_ignores: # Optional
    - sw-register.js
    - "fonts/**/*"